name: Build branches image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Build and Push Docker Image
        uses: docker/build-push-action@master
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          DOCKER_BUILD_SUMMARY: false
        with:
          context: .
          pull: true
          push: ${{ github.ref_name == 'main' }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/quasascale-frontend:cache-${{ github.ref_name }}
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/quasascale-frontend:cache-${{ github.ref_name }},mode=max
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quasascale-frontend:${{ github.ref_name }}
